x-labels: &labels
  labels:
    app.name: ${COMPOSE_PROJECT_NAME}

services:
  wikidb:
    extends:
      file: ../../common.yml
      service: base
    hostname: ${COMPOSE_PROJECT_NAME}.${WIKIDB_HOSTNAME}
    container_name: ${COMPOSE_PROJECT_NAME}-wikidb
    image: ${COMPOSE_PROJECT_NAME}/wikidb:${WIKIDB_VERSION}
    build:
      context: .
      dockerfile: wikidb.Dockerfile
      args:
        - WIKIDB_VERSION=${WIKIDB_VERSION}
        # - WIKIDB_CONFIG_PATH=${WIKIDB_CONFIG_PATH}
        - WIKIDB_HEALTHCHECK_PATH=${WIKIDB_HEALTHCHECK_PATH}
    ports:
      - ${WIKIDB_EXPOSED_PORT}:${WIKIDB_PORT}
    volumes:
      # - ./wikidb.conf:${WIKIDB_CONFIG_PATH}
      - ./wikidb-healthcheck.bash:${WIKIDB_HEALTHCHECK_PATH}
      - ${WIKIDB_VOLUME}:${WIKIDB_DATA_DIR}
    networks:
      default:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.${WIKIDB_HOSTNAME}
    env_file:
      - ./wikidb.env
    environment:
      POSTGRES_DB: ${WIKIDB_DB_NAME}
      POSTGRES_PASSWORD: ${WIKIDB_DB_PASSWORD}
      POSTGRES_USER: ${WIKIDB_DB_USER}
      PGPASSWORD: ${WIKIDB_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--data-checksums --locale=${LC_ALL} --encoding=UTF8"

volumes:
  wikidb_data:
    name: ${WIKIDB_VOLUME}
    driver: local
    <<: [*labels]
