#!/usr/bin/env bash
# Entrypoint to run the homelab system.
# SERVICES="redis redisinsight wikidb wiki mongodb"
SERVICES="mongo-express"

# Initialize command as an array
cmd=("docker" "compose")

# Add fixed parts of the command
cmd+=("--file" "homelab.yml")
cmd+=("--env-file" "homelab.env")
# cmd+=("--env-file" "redis/redis.env")
# cmd+=("--env-file" "redisinsight/redisinsight.env")
# cmd+=("--env-file" "wiki/wiki.env")
# cmd+=("--env-file" "wiki/wikidb/wikidb.env")
cmd+=("--env-file" "mongodb/mongodb.env")
cmd+=("--env-file" "mongodb/mongo-express/mongo-express.env")

# Build up the command based on conditional logic
# For example, we can add more services or options based on external conditions
# if [ "${SERVICES}" == "mongodb" ]; then
#     cmd+=("up" "${SERVICES}")
# else
#     cmd+=("up")
# fi

cmd+=("up" "${SERVICES}")

# Finally, append all additional arguments passed to the script
cmd+=("$@")

# Execute the constructed command
echo "Executing command: ${cmd[*]}"
"${cmd[@]}"

# docker compose \
#     --file homelab.yml \
#     --env-file homelab.env \
#     --env-file redis/redis.env \
#     --env-file redisinsight/redisinsight.env \
#     --env-file wiki/wiki.env \
#     --env-file wiki/wikidb/wikidb.env \
#     --env-file mongodb/mongodb.env \
#     up "${SERVICES}" \
#     "$@"
