#!/usr/bin/env bash
# Entrypoint to run the homelab system.
# SERVICES="redis redisinsight wikidb wiki mongodb"

# List of services
SERVICES="mongodb portainer"

# Initialize command as an array
cmd=("docker" "compose")

# Add fixed parts of the command
cmd+=("--file" "homelab.yml")
cmd+=("--env-file" "homelab.env")
# cmd+=("--env-file" "redis/redis.env")
# cmd+=("--env-file" "redisinsight/redisinsight.env")
# cmd+=("--env-file" "wiki/wiki.env")
# cmd+=("--env-file" "wiki/wikidb/wikidb.env")
cmd+=("--env-file" "mongodb/mongodb.env")
cmd+=("--env-file" "mongodb/mongo-express/mongo-express.env")
cmd+=("--env-file" "portainer/portainer.env")

# Split the SERVICES string into an array
IFS=' ' read -r -a service_array <<<"$SERVICES"

# Append each service to the cmd array
cmd+=("up")
for service in "${service_array[@]}"; do
    cmd+=("$service")
done

# Finally, append all additional arguments passed to the script
cmd+=("$@")

# Execute the constructed command
echo "Executing command: ${cmd[*]}"
"${cmd[@]}"

# docker compose \
#     --file homelab.yml \
#     --env-file homelab.env \
#     --env-file redis/redis.env \
#     --env-file redisinsight/redisinsight.env \
#     --env-file wiki/wiki.env \
#     --env-file wiki/wikidb/wikidb.env \
#     --env-file mongodb/mongodb.env \
#     up "${SERVICES}" \
#     "$@"
