x-labels: &labels
  labels:
    app.name: ${COMPOSE_PROJECT_NAME}

services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}-alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock --admin-password="$PORTAINER_ADMIN_PASSWORD"
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always
    networks:
      main-network:
        aliases:
          - portainer

volumes:
  portainer_data:
