services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /path/to/media:/media
      - /path/to/media2:/media2:ro
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  jellyfin-config:
    driver: local
    name: ${JELLYFIN_CONFIG_VOLUME}
  jellyfin-cache:
    driver: local
    name: ${JELLYFIN_CACHE_VOLUME}
